### PR TITLE
Bugfix: Use the actual struct size and not the pointer size

### PR DESCRIPTION
**Pull request by nbars**

### CODE REVIEW

**Review by tanneberger — APPROVED** [review]
Good Catch

Precisely the reason why I prefer `sizeof(actual_data_type)` over `sizeof(variable)`.

**Review by Nimuedaertya — COMMENTED** [review]
Preferring as well the solution `sizeof(trie_node)`

**Comment by waehlisch** [comment]
@nbars, maybe you can comment why you finally decided on `now: sizeof(*n)` instead of the preferences of @tanneberger and @Nimuedaertya ... in case questions pop up later.

**Comment by nbars** [comment]
Sure; The rtrlib is (or should be) formatted according to the kernel coding style. And the style mandates to use the `sizeof(*n)` notation.

**Pull request merged**
