### PR TITLE
scripts: update checkpatch

### PR DESCRIPTION
**Pull request by smlng**
updates `scripts/checkpatch.pl` to latest linux kernel version. See also discussion in #109

### CODE REVIEW

**Comment by fho** [comment]
The build fails because of new introduced style checks in checkpatch.pl

**Comment by smlng** [comment]
I know, this is WIP

**Comment by smlng** [comment]
@fho fixed it, have a look!

**Comment by fho** [comment]
Should we deactivate the --strict checkpatch option for all tests instead of only for unittests?
Than it would be more consistent.

**Comment by smlng** [comment]
@fho: I'd rather stick with `--strict` for as many parts as possible, especially for the main library. I mean we had no problems with the option so far, but due to `cmocka` unittests cannot comply.

**Comment by fho** [comment]
Ok, if we would like to keep --strict activated for tests in general, we can also ignore only the particular checks for the cmocka unittests that we can't fix.
like:

```
$ git diff
diff --git a/scripts/check-coding-style.sh b/scripts/check-coding-style.sh
index 3166672..bc2632c 100755
--- a/scripts/check-coding-style.sh
+++ b/scripts/check-coding-style.sh
@@ -29,8 +29,13 @@ fi
 cd $SCRIPT_DIR/..
 for i in $CHECKSOURCE; do
        echo "> check coding style of $i ..."
+       IGNORE="--ignore PREFER_KERNEL_TYPES"
+       if [[ $i == *"tests/unittests/"* ]]; then
+               IGNORE="$IGNORE --ignore CAMELCASE"
+       fi
+       echo "$i $IGNORE"
        $SCRIPT_DIR/checkpatch.pl -f --strict --no-tree --terse --show-types \
-               --ignore PREFER_KERNEL_TYPES $i
+               $IGNORE $i

        if [ $? -ne "0" ]; then
                EXIT_CODE=1

```

**Comment by smlng** [comment]
ah haven't seen the specific ignore for CAMELCASE

**Comment by smlng** [comment]
squashed

**Comment by smlng** [comment]
@fho, if you're happy please merge right away!

**Comment by fho** [comment]
merged

**Comment by smlng** [comment]
ah you merged directly circumventing Github

**Pull request closed without merging**
