### PR TITLE
add badges to README.md and ref to CONTRIBUTING

### PR DESCRIPTION
**Pull request by waehlisch**
### Contribution description

This PR adds badges to the README.md and a ref to the contributing guidelines.

### Testing procedure

https://github.com/waehlisch/rtrlib/blob/master/README.md

### CODE REVIEW

**Review by mroethke — COMMENTED** [review]
Do we really need flash badges? I usually find them to be somewhat annoying and rather useless.

**Comment by waehlisch** [comment]
yes. there are studies that show such badges may increase participation of third parties.

**Comment by waehlisch** [comment]
ping @mroethke?!

**Review by mroethke — APPROVED** [review]
ok

**Pull request merged**
