### PR TITLE
Bug and security fixes

### PR DESCRIPTION
**Pull request by nbars**

### CODE REVIEW

**Comment by waehlisch** [comment]
@nbars Thanks! However, the RP includes two commits that should not be included 705b3e9ee5d5bceb687d296b3e261485bf389b3c and 663c599bf61a5ee4d392bd1a5e11ca5c2a58ef4d. Can you please exclude them.

Furthermore, personally, I'm more in favor of splitting the PR into smaller PRs. But I think this time we can leave it as it is to make it not too complicated.

**Comment by nbars** [comment]
Could someone check the CI-Server?
```
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by waehlisch** [comment]
@nbars I think the problem is that your branch does not include .travis.yml. You should update with the master branch.

**Comment by waehlisch** [comment]
See PRs #49 #50 #51

**Pull request closed without merging**
